operator:
  # image of ngrok-operator
  image: "ghcr.io/paganuzzi/ngrokoperator"
  # tag of ngrok-operator image
  tag: "latest"
  # pullPolicy for operator image
  pullPolicy: "Always"
  # number of replica for deployment
  replica: 1
