name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Cache multiple paths
      uses: actions/cache@v2
      with:
        path: |
          /home
        key: ${{ runner.os }}-${{ hashFiles('**/lockfiles') }}

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.15

    - name: Build go binary
      run: go build -v -o ./build/bin/ ./cmd/manager/main.go

    # - name: Upload a Build Artifact
    #   uses: actions/upload-artifact@v2.2.3
    #   with:
    #     name: binario
    #     path: build/bin/main

    -  
      uses: docker/setup-buildx-action@v1
      id: buildx
      with:
        install: true
    -
      name: Build image
      id: build-image
      run: |
        cd build/
        docker build . # will run buildx
    
    -
      name: Login to GitHub Container Registry
      uses: docker/login-action@v1 
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Push To github
      id: push-to-github
      uses: redhat-actions/push-to-registry@v2
      with:
        image: ${{ steps.build-image.outputs.image }}
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}

