name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Cache multiple paths
      uses: actions/cache@v2
      with:
        path: |
          /home
        key: ${{ runner.os }}-${{ hashFiles('**/lockfiles') }}

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.15

    - name: Build
      run: go build -v -o ./build/bin/ ./cmd/manager/main.go

    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v2.2.3
      with:
        name: binario
        path: ./main

